import Head from 'next/head'
import Header from 'src/components/Header'
import Heading from 'src/pages/home/components/Heading'
import Footer from 'src/components/Footer'
import Services from 'src/pages/home/components/Services'
import OurValues from 'src/pages/home/components/OurValues'
import HowWorks from 'src/pages/home/components/HowWorks'
import Techs from 'src/pages/home/components/Techs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SEEDLAB.CL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Heading />
      <Services />
      <OurValues />
      <HowWorks />
      <Techs />
      <Footer />
    </div>
  )
}
