import Head from 'next/head'
import Header from 'src/components/Header'
import Heading from 'src/pages/home/components/Heading'
import Footer from 'src/components/Footer'
import Services from 'src/pages/home/components/Services'
import OurValues from 'src/pages/home/components/OurValues'
import HowWorks from 'src/pages/home/components/HowWorks'
import Techs from 'src/pages/home/components/Techs'
import IconWeb1 from 'public/icons/how-work-1.svg'
import IconWeb2 from 'public/icons/how-work-2.svg'
import IconWeb4 from 'public/icons/how-work-3.svg'


const cardServices = [
  {
    Icon: IconWeb1,
    url: '/desarrollo-web'
  },
  {
    Icon: IconWeb2,
  },
  {
    Icon: IconWeb1,
  },
  {
    Icon: IconWeb4,
  }
]

export default function Home() {
  return (
    <div>
      <Head>
        <title>SEEDLAB.CL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Heading />
      <Services title="Nuestros servicios" services={cardServices}/>
      <OurValues />
      <HowWorks />
      <Techs />
      <Footer />
    </div>
  )
}
