import Head from 'next/head'
import Image from 'next/image'
import Heading from '../src/pages/home/components/Heading'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SEEDLAB.CL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading />
    </div>
  )
}
